name: Build
on: push
jobs: 
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3v
    - uses: actions/upload-artifact@3v
        with:
          name: app
          path: public